import { ComponentType } from "react";
import {
  Building,
  Utensils,
  Hotel as HotelIcon,
  Dumbbell,
  Hospital as HospitalIcon,
  Activity,
  Scale,
  Home as HomeIcon,
  GraduationCap,
  BookOpen,
  Code2,
  Rocket,
  ShoppingBag,
  UserCheck,
  Layout,
  Scissors,
  Sparkles,
  Coffee,
  Compass,
  Hammer,
  Palette,
  Landmark,
  ShieldCheck,
  HeartHandshake,
  Factory,
  Tv,
  Sofa,
  Newspaper,
} from "lucide-react";

export const CATEGORY_ICON_MAP: Record<string, ComponentType<{ className?: string }>> = {
  business: Building,
  restaurant: Utensils,
  hotel: HotelIcon,
  gym: Dumbbell,
  hospital: HospitalIcon,
  clinic: Activity,
  lawyer: Scale,
  "real-estate": HomeIcon,
  school: GraduationCap,
  coaching: BookOpen,
  "software-company": Code2,
  "digital-agency": Rocket,
  ecommerce: ShoppingBag,
  portfolio: UserCheck,
  "landing-page": Layout,
  salon: Scissors,
  spa: Sparkles,
  cafe: Coffee,
  bakery: Coffee,
  travel: Compass,
  construction: Hammer,
  interior: Palette,
  architecture: Landmark,
  finance: ShieldCheck,
  insurance: ShieldCheck,
  ngo: HeartHandshake,
  manufacturing: Factory,
  electronics: Tv,
  furniture: Sofa,
  blog: BookOpen,
  news: Newspaper,
};

export const DESIGN_SYSTEM_TOKENS = {
  typography: {
    hero: "text-4xl sm:text-5xl lg:text-6xl font-extrabold tracking-tight leading-[1.1]",
    h1: "text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight",
    h2: "text-2xl sm:text-3xl lg:text-4xl font-bold tracking-tight",
    h3: "text-xl sm:text-2xl font-bold",
    h4: "text-lg font-semibold",
    bodyLarge: "text-base sm:text-lg leading-relaxed",
    body: "text-sm sm:text-base leading-relaxed",
    caption: "text-xs font-medium uppercase tracking-wider",
  },
  spacing: {
    sectionPadding: "py-16 sm:py-20 lg:py-24",
    containerMax: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8",
    gridGap: "gap-6 sm:gap-8 lg:gap-10",
  },
  buttons: {
    primary:
      "inline-flex items-center justify-center px-6 py-3.5 text-sm font-bold rounded-xl transition-all duration-200 shadow-md hover:shadow-lg focus:outline-none focus:ring-2 focus:ring-offset-2",
    secondary:
      "inline-flex items-center justify-center px-6 py-3.5 text-sm font-semibold rounded-xl border transition-all duration-200 hover:bg-slate-100 dark:hover:bg-slate-800",
    outline:
      "inline-flex items-center justify-center px-5 py-2.5 text-xs font-bold rounded-xl border border-current transition-all duration-200 hover:opacity-80",
  },
};
