import { CategoryId, TemplateConfig } from "./types";

export const CATEGORY_TEMPLATE_REGISTRY: Record<CategoryId, TemplateConfig> = {
  business: {
    id: "business",
    title: "Corporate Business",
    description: "Enterprise multi-page layout with company overview, services, client case studies, and corporate contact.",
    tag: "Corporate",
    iconName: "business",
    navigation: [
      { label: "Home", href: "/" },
      { label: "About", href: "/about" },
      { label: "Services", href: "/services" },
      { label: "Case Studies", href: "/case-studies" },
      { label: "Contact", href: "/contact", isCTA: true },
    ],
    pages: [
      { id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Main landing view with hero, company stats, and services.", sections: ["hero", "stats", "services", "case_studies", "testimonials", "cta"] },
      { id: "about", name: "About Us", filename: "about.html", description: "Company history, leadership team, and mission statement.", sections: ["about_hero", "mission", "team", "values"] },
      { id: "services", name: "Services", filename: "services.html", description: "Detailed service offerings and pricing tiers.", sections: ["services_grid", "pricing", "faq"] },
      { id: "contact", name: "Contact Us", filename: "contact.html", description: "Inquiry form, office map, and contact info.", sections: ["contact_form", "location_map"] },
    ],
    categoryUX: {
      primaryCTA: "Request Proposal",
      secondaryCTA: "Explore Services",
      heroHeadlinePlaceholder: "Empowering Modern Enterprises With Tailored Business Solutions",
      specializedComponents: ["CompanyStats", "CaseStudyGrid", "LeadershipTeam"],
      featuresList: ["Corporate Strategy", "Enterprise Architecture", "Consulting & Audit"],
      colorThemeFallback: "Corporate",
    },
    sections: ["hero", "stats", "services", "team", "testimonials", "cta"],
  },
  restaurant: {
    id: "restaurant",
    title: "Restaurant & Dining",
    description: "Culinary layout featuring interactive food menu, online table reservation, chef specialties, and photo gallery.",
    tag: "Food",
    iconName: "restaurant",
    navigation: [
      { label: "Home", href: "/" },
      { label: "Menu", href: "/menu" },
      { label: "Chef's Specials", href: "/specials" },
      { label: "Book Table", href: "/reservations", isCTA: true },
    ],
    pages: [
      { id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Dining hero, featured dishes, and reservation teaser.", sections: ["hero", "menu_teaser", "chef_showcase", "gallery", "reservations_cta"] },
      { id: "menu", name: "Food Menu", filename: "menu.html", description: "Categorized food menu with prices and dietary tags.", sections: ["menu_categories", "dietary_info"] },
      { id: "reservations", name: "Book Table", filename: "reservations.html", description: "Online table reservation form.", sections: ["reservation_form", "timing_info"] },
    ],
    categoryUX: {
      primaryCTA: "Book a Table",
      secondaryCTA: "View Menu",
      heroHeadlinePlaceholder: "Exquisite Culinary Delights & Unforgettable Dining Experiences",
      specializedComponents: ["FoodMenuGrid", "TableReservationForm", "ChefShowcase", "FoodGallery"],
      featuresList: ["Gourmet Dining", "Online Reservations", "Private Event Catering"],
      colorThemeFallback: "Luxury",
    },
    sections: ["hero", "menu", "chef", "gallery", "reservations"],
  },
  hotel: {
    id: "hotel",
    title: "Hotel & Resort",
    description: "Hospitality layout with luxury room showcases, amenity lists, dining info, and online room booking.",
    tag: "Hospitality",
    iconName: "hotel",
    navigation: [
      { label: "Home", href: "/" },
      { label: "Rooms & Suites", href: "/rooms" },
      { label: "Amenities", href: "/amenities" },
      { label: "Book Stay", href: "/booking", isCTA: true },
    ],
    pages: [
      { id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Resort hero, room preview, amenities, and guest reviews.", sections: ["hero", "room_preview", "amenities", "reviews"] },
      { id: "rooms", name: "Rooms", filename: "rooms.html", description: "Detailed room packages and pricing.", sections: ["room_grid", "specs"] },
      { id: "booking", name: "Book Stay", filename: "booking.html", description: "Date selector and room reservation.", sections: ["booking_form"] },
    ],
    categoryUX: {
      primaryCTA: "Check Availability",
      secondaryCTA: "Explore Suites",
      heroHeadlinePlaceholder: "Experience Unmatched Luxury & Serene Resort Hospitality",
      specializedComponents: ["RoomCardGrid", "AmenityBadges", "BookingDateForm", "DiningHighlights"],
      featuresList: ["Luxury Suites", "Infinity Pool & Spa", "24/7 Concierge Service"],
      colorThemeFallback: "Luxury",
    },
    sections: ["hero", "rooms", "amenities", "reviews", "booking"],
  },
  gym: {
    id: "gym",
    title: "Gym & Fitness Club",
    description: "High-energy fitness layout with workout programs, certified trainers, membership pricing, and BMI calculator.",
    tag: "Fitness",
    iconName: "gym",
    navigation: [
      { label: "Home", href: "/" },
      { label: "Programs", href: "/programs" },
      { label: "Trainers", href: "/trainers" },
      { label: "Join Now", href: "/membership", isCTA: true },
    ],
    pages: [
      { id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Fitness hero, workout programs, trainer grid, and BMI calculator.", sections: ["hero", "programs", "trainers", "bmi_calculator", "membership"] },
      { id: "programs", name: "Workouts", filename: "workouts.html", description: "Crossfit, Yoga, Strength, and Cardio schedules.", sections: ["program_list", "schedule_table"] },
      { id: "membership", name: "Join Gym", filename: "membership.html", description: "Membership pricing tiers and pass registration.", sections: ["pricing_table", "join_form"] },
    ],
    categoryUX: {
      primaryCTA: "Get Free Pass",
      secondaryCTA: "View Classes",
      heroHeadlinePlaceholder: "Transform Your Body & Unleash Peak Physical Performance",
      specializedComponents: ["ProgramCards", "TrainerShowcase", "MembershipPricing", "BMICalculator"],
      featuresList: ["Personal Training", "State-of-the-Art Equipment", "Group Cardio & Yoga"],
      colorThemeFallback: "Startup",
    },
    sections: ["hero", "programs", "trainers", "bmi", "pricing"],
  },
  hospital: {
    id: "hospital",
    title: "Hospital & Medical Center",
    description: "Healthcare layout with doctor directory, department showcase, emergency hotline, and appointment booking.",
    tag: "Healthcare",
    iconName: "hospital",
    navigation: [
      { label: "Home", href: "/" },
      { label: "Departments", href: "/departments" },
      { label: "Doctors", href: "/doctors" },
      { label: "Book Appointment", href: "/appointment", isCTA: true },
    ],
    pages: [
      { id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Medical hero, emergency contact, departments, and doctor list.", sections: ["hero", "emergency_banner", "departments", "doctors", "appointment"] },
      { id: "doctors", name: "Our Doctors", filename: "doctors.html", description: "Directory of specialist doctors and qualifications.", sections: ["doctor_grid"] },
      { id: "appointment", name: "Book Appointment", filename: "appointment.html", description: "Doctor selection and appointment scheduler.", sections: ["appointment_form"] },
    ],
    categoryUX: {
      primaryCTA: "Book Appointment",
      secondaryCTA: "Emergency Services",
      heroHeadlinePlaceholder: "Compassionate Healthcare & Advanced Medical Excellence",
      specializedComponents: ["DoctorDirectory", "EmergencyHotlineBanner", "DepartmentGrid", "AppointmentScheduler"],
      featuresList: ["24/7 Emergency Care", "Board-Certified Doctors", "Advanced ICU & Diagnostics"],
      colorThemeFallback: "White",
    },
    sections: ["hero", "emergency", "departments", "doctors", "appointment"],
  },
  clinic: {
    id: "clinic",
    title: "Specialist Clinic",
    description: "Focused clinic design for dental, eye, skin, or general healthcare practitioners.",
    tag: "Healthcare",
    iconName: "clinic",
    navigation: [
      { label: "Home", href: "/" },
      { label: "Services", href: "/services" },
      { label: "Doctor", href: "/about" },
      { label: "Book Consult", href: "/appointment", isCTA: true },
    ],
    pages: [
      { id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Clinic overview, doctor profile, treatments, and booking.", sections: ["hero", "treatments", "doctor_profile", "reviews", "booking"] },
    ],
    categoryUX: {
      primaryCTA: "Consult Doctor",
      secondaryCTA: "View Treatments",
      heroHeadlinePlaceholder: "Personalized Clinic Care For You & Your Family",
      specializedComponents: ["DoctorProfile", "TreatmentGrid", "AppointmentScheduler"],
      featuresList: ["Painless Dental Care", "Modern Diagnostics", "Personalized Attention"],
      colorThemeFallback: "White",
    },
    sections: ["hero", "treatments", "doctor", "booking"],
  },
  lawyer: {
    id: "lawyer",
    title: "Law Firm & Legal Practice",
    description: "Prestigious legal layout with practice areas, attorney credentials, case study results, and consultation booking.",
    tag: "Legal",
    iconName: "lawyer",
    navigation: [
      { label: "Home", href: "/" },
      { label: "Practice Areas", href: "/practice-areas" },
      { label: "Attorneys", href: "/attorneys" },
      { label: "Free Consultation", href: "/consultation", isCTA: true },
    ],
    pages: [
      { id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Legal hero, practice areas, track record, and attorney team.", sections: ["hero", "practice_areas", "case_results", "attorneys", "consultation"] },
      { id: "practice-areas", name: "Practice Areas", filename: "practice_areas.html", description: "Corporate law, litigation, IP, and family law details.", sections: ["practice_grid"] },
      { id: "consultation", name: "Consultation", filename: "consultation.html", description: "Case inquiry form.", sections: ["consultation_form"] },
    ],
    categoryUX: {
      primaryCTA: "Free Legal Consult",
      secondaryCTA: "View Practice Areas",
      heroHeadlinePlaceholder: "Defending Your Legal Rights With Uncompromising Commitment",
      specializedComponents: ["PracticeAreaGrid", "AttorneyProfiles", "CaseResultsCounter", "ConsultationForm"],
      featuresList: ["98% Case Success Rate", "Experienced Trial Lawyers", "Confidential Consultation"],
      colorThemeFallback: "Corporate",
    },
    sections: ["hero", "practice_areas", "attorneys", "consultation"],
  },
  "real-estate": {
    id: "real-estate",
    title: "Real Estate & Property",
    description: "Property portal with featured listings, interactive filters, spec badges, and site tour booking.",
    tag: "Property",
    iconName: "real-estate",
    navigation: [
      { label: "Home", href: "/" },
      { label: "Properties", href: "/properties" },
      { label: "Projects", href: "/projects" },
      { label: "Schedule Tour", href: "/tour", isCTA: true },
    ],
    pages: [
      { id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Property hero, search filter, featured homes, and agent contacts.", sections: ["hero", "search_filter", "featured_properties", "agents", "tour_cta"] },
      { id: "properties", name: "Listings", filename: "properties.html", description: "Filterable property catalog.", sections: ["property_grid"] },
      { id: "tour", name: "Book Tour", filename: "tour.html", description: "Site visit request form.", sections: ["tour_form"] },
    ],
    categoryUX: {
      primaryCTA: "Book Site Tour",
      secondaryCTA: "Browse Properties",
      heroHeadlinePlaceholder: "Discover Premium Residential & Commercial Properties",
      specializedComponents: ["PropertyShowcaseGrid", "PropertySpecBadges", "InteractiveFilterBar", "TourRequestForm"],
      featuresList: ["Prime City Locations", "RERA Approved Projects", "Flexible Financing Options"],
      colorThemeFallback: "White",
    },
    sections: ["hero", "properties", "agents", "tour"],
  },
  school: {
    id: "school",
    title: "School & Academy",
    description: "Educational institution layout with academic curriculum, faculty grid, campus facilities, and admission form.",
    tag: "Education",
    iconName: "school",
    navigation: [
      { label: "Home", href: "/" },
      { label: "Academics", href: "/academics" },
      { label: "Campus", href: "/campus" },
      { label: "Apply Now", href: "/admissions", isCTA: true },
    ],
    pages: [
      { id: "home", name: "Home", filename: "index.html", isDefault: true, description: "School hero, achievements, academic programs, and campus gallery.", sections: ["hero", "stats", "programs", "gallery", "admissions"] },
    ],
    categoryUX: {
      primaryCTA: "Apply for Admission",
      secondaryCTA: "Explore Curriculum",
      heroHeadlinePlaceholder: "Nurturing Tomorrow's Leaders Through Holistic Education",
      specializedComponents: ["AcademicProgramGrid", "FacultyShowcase", "AdmissionForm"],
      featuresList: ["STEM & Robotics Labs", "Global Exchange Programs", "100% Academic Excellence"],
      colorThemeFallback: "White",
    },
    sections: ["hero", "programs", "faculty", "admissions"],
  },
  coaching: {
    id: "coaching",
    title: "Coaching & Test Prep",
    description: "Institute layout for competitive exam coaching, course details, batch schedules, and free trial demo.",
    tag: "Education",
    iconName: "coaching",
    navigation: [
      { label: "Home", href: "/" },
      { label: "Courses", href: "/courses" },
      { label: "Results", href: "/results" },
      { label: "Free Demo", href: "/demo", isCTA: true },
    ],
    pages: [
      { id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Coaching hero, top rankers, course packages, and demo class booking.", sections: ["hero", "rankers", "courses", "demo_form"] },
    ],
    categoryUX: {
      primaryCTA: "Book Free Demo",
      secondaryCTA: "View Courses",
      heroHeadlinePlaceholder: "Master Competitive Exams With Expert Mentorship & Proven Results",
      specializedComponents: ["RankerTestimonials", "CourseBatchGrid", "DemoClassForm"],
      featuresList: ["Expert Faculty", "Comprehensive Test Series", "Personalized Doubt Solving"],
      colorThemeFallback: "Startup",
    },
    sections: ["hero", "courses", "rankers", "demo"],
  },
  "software-company": {
    id: "software-company",
    title: "Software & SaaS Company",
    description: "SaaS & Dev agency layout featuring product tech specs, client case studies, process timeline, and demo booking.",
    tag: "SaaS",
    iconName: "software-company",
    navigation: [
      { label: "Home", href: "/" },
      { label: "Services", href: "/services" },
      { label: "Portfolio", href: "/portfolio" },
      { label: "Tech Stack", href: "/tech" },
      { label: "Get Quote", href: "/contact", isCTA: true },
    ],
    pages: [
      { id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Software hero, tech stack, client logos, case studies, and contact.", sections: ["hero", "tech_stack", "services", "case_studies", "pricing", "contact"] },
      { id: "services", name: "Services", filename: "services.html", description: "Custom dev, cloud, mobile apps, and DevOps.", sections: ["services_list"] },
      { id: "portfolio", name: "Portfolio", filename: "portfolio.html", description: "Software projects showcase.", sections: ["project_grid"] },
    ],
    categoryUX: {
      primaryCTA: "Schedule Demo",
      secondaryCTA: "View Stack",
      heroHeadlinePlaceholder: "Building Scalable Cloud Applications & High-Performance Software",
      specializedComponents: ["TechStackBadges", "SaaSProductPreview", "ProcessTimeline", "SaaSPricingMatrix"],
      featuresList: ["Cloud Native Architecture", "99.99% Uptime Guarantee", "24/7 DevOps Support"],
      colorThemeFallback: "Dark",
    },
    sections: ["hero", "tech", "services", "case_studies", "pricing"],
  },
  "digital-agency": {
    id: "digital-agency",
    title: "Digital Marketing Agency",
    description: "Creative agency layout with portfolio grid, client case studies, service packages, and lead form.",
    tag: "Agency",
    iconName: "digital-agency",
    navigation: [
      { label: "Home", href: "/" },
      { label: "Services", href: "/services" },
      { label: "Work", href: "/work" },
      { label: "Hire Us", href: "/contact", isCTA: true },
    ],
    pages: [
      { id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Agency hero, client logos, project grid, services, and lead contact.", sections: ["hero", "portfolio_grid", "services", "testimonials", "contact"] },
    ],
    categoryUX: {
      primaryCTA: "Start Project",
      secondaryCTA: "View Our Work",
      heroHeadlinePlaceholder: "We Scale Brands Through Data-Driven Design & High-Growth Marketing",
      specializedComponents: ["AgencyPortfolioGrid", "ClientTestimonials", "LeadGenForm"],
      featuresList: ["SEO & Content Growth", "Performance PPC Ads", "Brand Identity Design"],
      colorThemeFallback: "Startup",
    },
    sections: ["hero", "work", "services", "contact"],
  },
  ecommerce: {
    id: "ecommerce",
    title: "E-Commerce Store",
    description: "Retail store layout featuring product showcase grid, category tabs, cart teaser, and checkout preview.",
    tag: "Retail",
    iconName: "ecommerce",
    navigation: [
      { label: "Home", href: "/" },
      { label: "Shop", href: "/shop" },
      { label: "Categories", href: "/categories" },
      { label: "Cart (0)", href: "/cart", isCTA: true },
    ],
    pages: [
      { id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Store hero, trending products, categories, and customer reviews.", sections: ["hero", "trending_products", "categories", "guarantees"] },
      { id: "shop", name: "Shop Catalog", filename: "shop.html", description: "Filterable product listing.", sections: ["product_catalog"] },
    ],
    categoryUX: {
      primaryCTA: "Shop Collection",
      secondaryCTA: "View Sale Items",
      heroHeadlinePlaceholder: "Premium Handcrafted Products Delivered Directly To Your Doorstep",
      specializedComponents: ["ProductCatalogGrid", "CategoryFilterTabs", "StoreGuarantees"],
      featuresList: ["Free Express Shipping", "Easy 30-Day Returns", "Secure SSL Payments"],
      colorThemeFallback: "White",
    },
    sections: ["hero", "products", "categories", "guarantees"],
  },
  portfolio: {
    id: "portfolio",
    title: "Personal Portfolio",
    description: "Creative personal site for developers, designers, writers, and consultants.",
    tag: "Creative",
    iconName: "portfolio",
    navigation: [
      { label: "Home", href: "/" },
      { label: "Projects", href: "/projects" },
      { label: "About", href: "/about" },
      { label: "Let's Talk", href: "/contact", isCTA: true },
    ],
    pages: [
      { id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Personal intro hero, project cards, skills grid, and contact.", sections: ["hero", "projects", "skills", "contact"] },
    ],
    categoryUX: {
      primaryCTA: "View Projects",
      secondaryCTA: "Download CV",
      heroHeadlinePlaceholder: "Hi, I Build Exceptional Digital Experiences & Modern Web Solutions",
      specializedComponents: ["ProjectShowcase", "SkillsPillGrid", "DirectMessageForm"],
      featuresList: ["Full-Stack Development", "UI/UX Design Systems", "API Architecture"],
      colorThemeFallback: "Dark",
    },
    sections: ["hero", "projects", "skills", "contact"],
  },
  "landing-page": {
    id: "landing-page",
    title: "High-Converting Landing Page",
    description: "Focused single-page funnel optimized for lead generation, product launches, and ad campaigns.",
    tag: "Marketing",
    iconName: "landing-page",
    navigation: [
      { label: "Features", href: "#features" },
      { label: "Social Proof", href: "#testimonials" },
      { label: "Pricing", href: "#pricing" },
      { label: "Get Started", href: "#cta", isCTA: true },
    ],
    pages: [
      { id: "home", name: "Home", filename: "index.html", isDefault: true, description: "High-impact hero, problem-solution, feature list, pricing, and strong CTA.", sections: ["hero", "social_proof", "features", "pricing", "faq", "cta"] },
    ],
    categoryUX: {
      primaryCTA: "Get Started Free",
      secondaryCTA: "Watch 2-Min Video",
      heroHeadlinePlaceholder: "Turn Traffic Into Loyal Customers With Our All-In-One Conversion Engine",
      specializedComponents: ["ProblemSolutionCard", "HighImpactCTA", "PricingTierCards"],
      featuresList: ["Zero Setup Time", "Instant Integration", "Cancel Anytime"],
      colorThemeFallback: "Gradient",
    },
    sections: ["hero", "features", "pricing", "cta"],
  },
  salon: {
    id: "salon",
    title: "Beauty Salon & Spa",
    description: "Wellness layout with service menu, stylist profiles, price list, and online appointment booking.",
    tag: "Beauty",
    iconName: "salon",
    navigation: [
      { label: "Home", href: "/" },
      { label: "Services", href: "/services" },
      { label: "Stylists", href: "/team" },
      { label: "Book Appointment", href: "/booking", isCTA: true },
    ],
    pages: [
      { id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Salon hero, service list, price grid, and booking form.", sections: ["hero", "services", "stylists", "booking"] },
    ],
    categoryUX: {
      primaryCTA: "Book Appointment",
      secondaryCTA: "View Price List",
      heroHeadlinePlaceholder: "Pamper Yourself With Luxury Hair, Skin & Wellness Treatments",
      specializedComponents: ["SalonServiceMenu", "StylistShowcase", "AppointmentScheduler"],
      featuresList: ["Organic Care Products", "Certified Hair Stylists", "Relaxing Spa Ambiance"],
      colorThemeFallback: "White",
    },
    sections: ["hero", "services", "stylists", "booking"],
  },
  spa: {
    id: "spa",
    title: "Wellness Spa & Retreat",
    description: "Serene spa layout featuring massage packages, aromatherapy treatments, and online session booking.",
    tag: "Beauty",
    iconName: "spa",
    navigation: [
      { label: "Home", href: "/" },
      { label: "Treatments", href: "/treatments" },
      { label: "Book Session", href: "/booking", isCTA: true },
    ],
    pages: [{ id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Spa hero, treatment menu, and session booking.", sections: ["hero", "treatments", "booking"] }],
    categoryUX: { primaryCTA: "Book Session", secondaryCTA: "Explore Treatments", heroHeadlinePlaceholder: "Rejuvenate Your Mind, Body & Soul In Serene Luxury", specializedComponents: ["TreatmentMenu", "SessionBooking"], featuresList: ["Aromatherapy", "Hot Stone Massage", "Hydrotherapy"], colorThemeFallback: "Luxury" },
    sections: ["hero", "treatments", "booking"],
  },
  cafe: {
    id: "cafe",
    title: "Artisanal Cafe & Coffee Shop",
    description: "Cozy coffee shop site showcasing specialty brews, bakery menu, store location, and hours.",
    tag: "Food",
    iconName: "cafe",
    navigation: [{ label: "Home", href: "/" }, { label: "Coffee Menu", href: "/menu" }, { label: "Visit Us", href: "/contact", isCTA: true }],
    pages: [{ id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Coffee hero, brew list, location, and hours.", sections: ["hero", "menu", "hours"] }],
    categoryUX: { primaryCTA: "Order Ahead", secondaryCTA: "See Brew Menu", heroHeadlinePlaceholder: "Freshly Roasted Organic Coffee & Artisanal Pastries", specializedComponents: ["CoffeeMenu", "LocationHours"], featuresList: ["Single-Origin Beans", "Fresh Daily Pastries", "Free High-Speed Wi-Fi"], colorThemeFallback: "White" },
    sections: ["hero", "menu", "hours"],
  },
  bakery: {
    id: "bakery",
    title: "Artisan Bakery & Cake Shop",
    description: "Custom cake and bakery website featuring custom order forms, gallery, and daily baked goods.",
    tag: "Food",
    iconName: "bakery",
    navigation: [{ label: "Home", href: "/" }, { label: "Cakes & Pastries", href: "/menu" }, { label: "Custom Order", href: "/order", isCTA: true }],
    pages: [{ id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Bakery hero, custom cakes, and daily menu.", sections: ["hero", "cake_gallery", "order_form"] }],
    categoryUX: { primaryCTA: "Order Custom Cake", secondaryCTA: "View Gallery", heroHeadlinePlaceholder: "Delicious Handcrafted Cakes & Fresh Bakery Delights", specializedComponents: ["CakeGallery", "CustomOrderForm"], featuresList: ["100% Eggless Options", "Custom Birthday Designs", "Same-Day Delivery"], colorThemeFallback: "Startup" },
    sections: ["hero", "cakes", "order"],
  },
  travel: {
    id: "travel",
    title: "Travel & Tour Agency",
    description: "Tourism layout with tour package cards, destination guides, itinerary breakdowns, and booking form.",
    tag: "Tourism",
    iconName: "travel",
    navigation: [{ label: "Home", href: "/" }, { label: "Tour Packages", href: "/packages" }, { label: "Book Tour", href: "/booking", isCTA: true }],
    pages: [{ id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Travel hero, destination packages, and tour inquiry.", sections: ["hero", "packages", "inquiry"] }],
    categoryUX: { primaryCTA: "Book Package", secondaryCTA: "View Destinations", heroHeadlinePlaceholder: "Explore Breathtaking Destinations & Curated Travel Experiences", specializedComponents: ["TourPackageGrid", "ItineraryBreakdown"], featuresList: ["All-Inclusive Tours", "24/7 Travel Guide", "Best Price Guarantee"], colorThemeFallback: "White" },
    sections: ["hero", "packages", "inquiry"],
  },
  construction: {
    id: "construction",
    title: "Construction & Engineering",
    description: "Heavy industry & builder site with ongoing projects, equipment catalog, safety records, and quote request.",
    tag: "Industry",
    iconName: "construction",
    navigation: [{ label: "Home", href: "/" }, { label: "Projects", href: "/projects" }, { label: "Get Quote", href: "/contact", isCTA: true }],
    pages: [{ id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Construction hero, project portfolio, and estimate request.", sections: ["hero", "projects", "quote"] }],
    categoryUX: { primaryCTA: "Request Estimate", secondaryCTA: "View Projects", heroHeadlinePlaceholder: "Engineering World-Class Commercial & Residential Infrastructure", specializedComponents: ["ProjectPortfolioGrid", "EstimateForm"], featuresList: ["On-Time Completion", "ISO Certified Safety", "Turnkey EPC Services"], colorThemeFallback: "Corporate" },
    sections: ["hero", "projects", "quote"],
  },
  interior: {
    id: "interior",
    title: "Interior Design Studio",
    description: "Aesthetic studio site showcasing residential interior portfolios, 3D render designs, and design consultation.",
    tag: "Creative",
    iconName: "interior",
    navigation: [{ label: "Home", href: "/" }, { label: "Portfolio", href: "/portfolio" }, { label: "Book Consult", href: "/contact", isCTA: true }],
    pages: [{ id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Interior hero, 3D design showcase, and consultation.", sections: ["hero", "portfolio", "consult"] }],
    categoryUX: { primaryCTA: "Book Design Consult", secondaryCTA: "View 3D Works", heroHeadlinePlaceholder: "Transforming Spaces Into Elegant Modern Masterpieces", specializedComponents: ["InteriorGallery", "ConsultForm"], featuresList: ["Custom 3D Visualization", "Turnkey Furniture Execution", "10-Year Warranty"], colorThemeFallback: "Minimal" },
    sections: ["hero", "portfolio", "consult"],
  },
  architecture: {
    id: "architecture",
    title: "Architecture Firm",
    description: "Architectural design site displaying masterplans, urban blueprints, built projects, and inquiry form.",
    tag: "Creative",
    iconName: "architecture",
    navigation: [{ label: "Home", href: "/" }, { label: "Works", href: "/works" }, { label: "Inquire", href: "/contact", isCTA: true }],
    pages: [{ id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Architectural hero, blueprint gallery, and inquiry.", sections: ["hero", "works", "inquiry"] }],
    categoryUX: { primaryCTA: "Consult Architect", secondaryCTA: "Browse Works", heroHeadlinePlaceholder: "Innovative Sustainable Architecture & Urban Design Solutions", specializedComponents: ["BlueprintGallery"], featuresList: ["Sustainable Green Design", "BIM 3D Modeling", "Urban Masterplanning"], colorThemeFallback: "Minimal" },
    sections: ["hero", "works", "inquiry"],
  },
  finance: {
    id: "finance",
    title: "Financial Services & Advisory",
    description: "Financial advisory site with investment planning, wealth management, loan calculators, and consult booking.",
    tag: "Finance",
    iconName: "finance",
    navigation: [{ label: "Home", href: "/" }, { label: "Services", href: "/services" }, { label: "Book Consult", href: "/contact", isCTA: true }],
    pages: [{ id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Financial hero, wealth plans, and consultation.", sections: ["hero", "services", "consult"] }],
    categoryUX: { primaryCTA: "Book Financial Review", secondaryCTA: "Explore Advisory", heroHeadlinePlaceholder: "Strategic Wealth Management & Secure Financial Planning", specializedComponents: ["FinancialPlanCards", "LoanCalculator"], featuresList: ["SEBI Registered Advisors", "Tax Optimization", "Portfolio Diversification"], colorThemeFallback: "Corporate" },
    sections: ["hero", "services", "consult"],
  },
  insurance: {
    id: "insurance",
    title: "Insurance Agency",
    description: "Insurance portal featuring health, motor, and life policy comparisons with instant quote generator.",
    tag: "Finance",
    iconName: "insurance",
    navigation: [{ label: "Home", href: "/" }, { label: "Policies", href: "/policies" }, { label: "Get Quote", href: "/quote", isCTA: true }],
    pages: [{ id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Insurance hero, policy finder, and quote calculator.", sections: ["hero", "policies", "quote"] }],
    categoryUX: { primaryCTA: "Get Instant Quote", secondaryCTA: "Compare Policies", heroHeadlinePlaceholder: "Protect What Matters Most With Comprehensive Insurance Coverage", specializedComponents: ["QuoteCalculatorForm"], featuresList: ["Cashless Claims", "24/7 Claim Assistance", "Lowest Premium Rates"], colorThemeFallback: "White" },
    sections: ["hero", "policies", "quote"],
  },
  ngo: {
    id: "ngo",
    title: "NGO & Non-Profit Foundation",
    description: "Social cause site with active campaign drives, donation portal, volunteer signup, and impact reports.",
    tag: "Community",
    iconName: "ngo",
    navigation: [{ label: "Home", href: "/" }, { label: "Causes", href: "/causes" }, { label: "Donate Now", href: "/donate", isCTA: true }],
    pages: [{ id: "home", name: "Home", filename: "index.html", isDefault: true, description: "NGO hero, active causes, impact metrics, and donation CTA.", sections: ["hero", "causes", "impact", "donate"] }],
    categoryUX: { primaryCTA: "Donate Now", secondaryCTA: "Become Volunteer", heroHeadlinePlaceholder: "Empowering Communities & Driving Meaningful Social Change", specializedComponents: ["CauseCardGrid", "DonationPortal"], featuresList: ["100% Transparent Funding", "80G Tax Exemption", "Direct Community Impact"], colorThemeFallback: "White" },
    sections: ["hero", "causes", "impact", "donate"],
  },
  manufacturing: {
    id: "manufacturing",
    title: "Industrial Manufacturing",
    description: "B2B factory site with equipment catalogs, ISO quality certifications, global export info, and RFQ form.",
    tag: "Industry",
    iconName: "manufacturing",
    navigation: [{ label: "Home", href: "/" }, { label: "Products", href: "/products" }, { label: "Request RFQ", href: "/rfq", isCTA: true }],
    pages: [{ id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Factory hero, product catalog, and RFQ form.", sections: ["hero", "products", "rfq"] }],
    categoryUX: { primaryCTA: "Request RFQ Quote", secondaryCTA: "View Catalog", heroHeadlinePlaceholder: "Precision Industrial Manufacturing & Global OEM Supply", specializedComponents: ["ProductCatalogGrid", "RFQForm"], featuresList: ["ISO 9001:2015 Certified", "High-Volume Production", "Global Export Logistics"], colorThemeFallback: "Corporate" },
    sections: ["hero", "products", "rfq"],
  },
  electronics: {
    id: "electronics",
    title: "Electronics & Gadgets",
    description: "Tech hardware site with product specs, comparison charts, warranty registration, and support docs.",
    tag: "Retail",
    iconName: "electronics",
    navigation: [{ label: "Home", href: "/" }, { label: "Gadgets", href: "/gadgets" }, { label: "Support", href: "/support", isCTA: true }],
    pages: [{ id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Electronics hero, spec breakdown, and support.", sections: ["hero", "gadgets", "specs"] }],
    categoryUX: { primaryCTA: "Buy Now", secondaryCTA: "View Specs", heroHeadlinePlaceholder: "Next-Generation Smart Consumer Electronics & Wearables", specializedComponents: ["TechSpecsGrid"], featuresList: ["2-Year Warranty", "AI Smart Integration", "Free Nationwide Shipping"], colorThemeFallback: "Dark" },
    sections: ["hero", "gadgets", "specs"],
  },
  furniture: {
    id: "furniture",
    title: "Modern Furniture Store",
    description: "Showroom site featuring wooden furniture collections, room setups, custom sofa builders, and catalog download.",
    tag: "Retail",
    iconName: "furniture",
    navigation: [{ label: "Home", href: "/" }, { label: "Collections", href: "/collections" }, { label: "Visit Showroom", href: "/contact", isCTA: true }],
    pages: [{ id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Furniture hero, category catalog, and showroom info.", sections: ["hero", "collections", "contact"] }],
    categoryUX: { primaryCTA: "Explore Catalog", secondaryCTA: "Visit Showroom", heroHeadlinePlaceholder: "Ergonomic Handcrafted Furniture For Homes & Workspaces", specializedComponents: ["FurnitureCatalogGrid"], featuresList: ["Solid Teak Wood", "Custom Fabrics & Sizes", "Free Assembly Included"], colorThemeFallback: "White" },
    sections: ["hero", "collections", "contact"],
  },
  blog: {
    id: "blog",
    title: "Blog & Content Publication",
    description: "Editorial platform with featured articles, category filters, author bio widgets, and newsletter signup.",
    tag: "Content",
    iconName: "blog",
    navigation: [{ label: "Home", href: "/" }, { label: "Articles", href: "/articles" }, { label: "Subscribe", href: "/subscribe", isCTA: true }],
    pages: [{ id: "home", name: "Home", filename: "index.html", isDefault: true, description: "Editorial hero, latest articles, and newsletter form.", sections: ["hero", "articles", "newsletter"] }],
    categoryUX: { primaryCTA: "Subscribe Newsletter", secondaryCTA: "Read Featured", heroHeadlinePlaceholder: "In-Depth Insights, Tech Trends & Thought Leadership", specializedComponents: ["ArticleCardGrid", "NewsletterWidget"], featuresList: ["Daily Industry News", "Curated Expert Opinion", "Zero Ad Clutter"], colorThemeFallback: "White" },
    sections: ["hero", "articles", "newsletter"],
  },
  news: {
    id: "news",
    title: "News & Media Portal",
    description: "Daily newspaper portal with breaking news ticker, trending headlines, multi-category tabs, and video news.",
    tag: "Media",
    iconName: "news",
    navigation: [{ label: "Home", href: "/" }, { label: "World", href: "/world" }, { label: "Tech", href: "/tech" }, { label: "Live News", href: "/live", isCTA: true }],
    pages: [{ id: "home", name: "Home", filename: "index.html", isDefault: true, description: "News ticker, lead headlines, and category news grid.", sections: ["ticker", "hero", "news_grid"] }],
    categoryUX: { primaryCTA: "Watch Live", secondaryCTA: "Top Headlines", heroHeadlinePlaceholder: "Real-Time Breaking News, World Headlines & In-Depth Reporting", specializedComponents: ["NewsTicker", "HeadlinesGrid"], featuresList: ["Verified Journalists", "24/7 Breaking Updates", "Unbiased Coverage"], colorThemeFallback: "Minimal" },
    sections: ["ticker", "hero", "news"],
  },
};

export class TemplateRegistry {
  static getTemplate(categoryId: string): TemplateConfig {
    const normalizedKey = (categoryId || "business").toLowerCase().trim() as CategoryId;
    return CATEGORY_TEMPLATE_REGISTRY[normalizedKey] || CATEGORY_TEMPLATE_REGISTRY.business;
  }

  static getAllTemplates(): TemplateConfig[] {
    return Object.values(CATEGORY_TEMPLATE_REGISTRY);
  }

  static getCategoryPages(categoryId: string) {
    const template = this.getTemplate(categoryId);
    return template.pages;
  }
}
