import { ThemeId, ThemeTokenMap } from "./types";

export const THEME_TOKEN_REGISTRY: Record<ThemeId, ThemeTokenMap> = {
  White: {
    id: "White",
    name: "White",
    bgMain: "bg-white",
    bgSectionAlt: "bg-slate-50",
    bgCard: "bg-white",
    bgNav: "bg-white/90 backdrop-blur-md border-slate-200",
    textHeading: "text-slate-900",
    textBody: "text-slate-700",
    textMuted: "text-slate-500",
    borderPrimary: "border-slate-200",
    borderAccent: "border-slate-300",
    accentPrimary: "bg-slate-900",
    accentHover: "hover:bg-slate-800",
    accentText: "text-white",
    shadowLevel: "shadow-sm hover:shadow-md",
    radiusStyle: "rounded-2xl",
    isDark: false,
  },
  Dark: {
    id: "Dark",
    name: "Dark",
    bgMain: "bg-slate-950",
    bgSectionAlt: "bg-slate-900",
    bgCard: "bg-slate-900/90",
    bgNav: "bg-slate-950/90 backdrop-blur-md border-slate-800",
    textHeading: "text-white",
    textBody: "text-slate-300",
    textMuted: "text-slate-400",
    borderPrimary: "border-slate-800",
    borderAccent: "border-slate-700",
    accentPrimary: "bg-blue-600",
    accentHover: "hover:bg-blue-500",
    accentText: "text-white",
    shadowLevel: "shadow-lg shadow-black/40",
    radiusStyle: "rounded-2xl",
    isDark: true,
  },
  Corporate: {
    id: "Corporate",
    name: "Corporate",
    bgMain: "bg-slate-50",
    bgSectionAlt: "bg-white",
    bgCard: "bg-white",
    bgNav: "bg-slate-900 text-white border-slate-800",
    textHeading: "text-slate-900",
    textBody: "text-slate-700",
    textMuted: "text-slate-500",
    borderPrimary: "border-slate-200",
    borderAccent: "border-blue-900/20",
    accentPrimary: "bg-slate-900",
    accentHover: "hover:bg-slate-800",
    accentText: "text-white",
    shadowLevel: "shadow-sm border border-slate-200",
    radiusStyle: "rounded-xl",
    isDark: false,
  },
  Startup: {
    id: "Startup",
    name: "Startup",
    bgMain: "bg-white",
    bgSectionAlt: "bg-orange-50/40",
    bgCard: "bg-white",
    bgNav: "bg-white/90 backdrop-blur-md border-orange-100",
    textHeading: "text-slate-900",
    textBody: "text-slate-700",
    textMuted: "text-slate-500",
    borderPrimary: "border-orange-100",
    borderAccent: "border-orange-300",
    accentPrimary: "bg-orange-600",
    accentHover: "hover:bg-orange-500",
    accentText: "text-white",
    shadowLevel: "shadow-md shadow-orange-500/5",
    radiusStyle: "rounded-3xl",
    isDark: false,
  },
  Luxury: {
    id: "Luxury",
    name: "Luxury",
    bgMain: "bg-stone-950",
    bgSectionAlt: "bg-stone-900",
    bgCard: "bg-stone-900/90",
    bgNav: "bg-stone-950/90 backdrop-blur-md border-amber-900/30",
    textHeading: "text-amber-100",
    textBody: "text-stone-300",
    textMuted: "text-amber-200/60",
    borderPrimary: "border-amber-900/30",
    borderAccent: "border-amber-500/50",
    accentPrimary: "bg-gradient-to-r from-amber-600 to-amber-500",
    accentHover: "hover:from-amber-500 hover:to-amber-400",
    accentText: "text-stone-950 font-bold",
    shadowLevel: "shadow-xl shadow-amber-950/50",
    radiusStyle: "rounded-xl",
    isDark: true,
  },
  Glass: {
    id: "Glass",
    name: "Glass",
    bgMain: "bg-gradient-to-br from-indigo-50/30 via-white to-purple-50/30",
    bgSectionAlt: "bg-white/40 backdrop-blur-md",
    bgCard: "bg-white/70 backdrop-blur-xl",
    bgNav: "bg-white/60 backdrop-blur-xl border-white/50",
    textHeading: "text-slate-900",
    textBody: "text-slate-700",
    textMuted: "text-slate-500",
    borderPrimary: "border-white/60",
    borderAccent: "border-indigo-200/80",
    accentPrimary: "bg-indigo-600",
    accentHover: "hover:bg-indigo-500",
    accentText: "text-white",
    shadowLevel: "shadow-lg shadow-indigo-500/10 backdrop-blur-md",
    radiusStyle: "rounded-2xl",
    isDark: false,
  },
  Gradient: {
    id: "Gradient",
    name: "Gradient",
    bgMain: "bg-slate-950",
    bgSectionAlt: "bg-gradient-to-r from-purple-950/40 via-slate-900 to-indigo-950/40",
    bgCard: "bg-slate-900/90 border border-purple-800/30",
    bgNav: "bg-slate-950/90 backdrop-blur-md border-purple-800/30",
    textHeading: "text-white",
    textBody: "text-slate-300",
    textMuted: "text-purple-300/60",
    borderPrimary: "border-purple-900/30",
    borderAccent: "border-purple-500/50",
    accentPrimary: "bg-gradient-to-r from-purple-600 via-indigo-600 to-blue-600",
    accentHover: "hover:opacity-90",
    accentText: "text-white",
    shadowLevel: "shadow-xl shadow-purple-950/40",
    radiusStyle: "rounded-2xl",
    isDark: true,
  },
  Minimal: {
    id: "Minimal",
    name: "Minimal",
    bgMain: "bg-white",
    bgSectionAlt: "bg-slate-100/70",
    bgCard: "bg-slate-50",
    bgNav: "bg-white border-slate-300",
    textHeading: "text-slate-950 font-black",
    textBody: "text-slate-800",
    textMuted: "text-slate-500",
    borderPrimary: "border-slate-300",
    borderAccent: "border-slate-900",
    accentPrimary: "bg-slate-950",
    accentHover: "hover:bg-slate-800",
    accentText: "text-white",
    shadowLevel: "shadow-none border border-slate-300",
    radiusStyle: "rounded-none",
    isDark: false,
  },
  Premium: {
    id: "Premium",
    name: "Premium",
    bgMain: "bg-slate-900",
    bgSectionAlt: "bg-slate-950",
    bgCard: "bg-slate-800/80 border border-emerald-500/20",
    bgNav: "bg-slate-900/90 backdrop-blur-md border-emerald-500/20",
    textHeading: "text-emerald-50",
    textBody: "text-slate-300",
    textMuted: "text-emerald-300/60",
    borderPrimary: "border-emerald-900/40",
    borderAccent: "border-emerald-500/40",
    accentPrimary: "bg-emerald-500",
    accentHover: "hover:bg-emerald-400",
    accentText: "text-slate-950 font-bold",
    shadowLevel: "shadow-xl shadow-emerald-950/30",
    radiusStyle: "rounded-2xl",
    isDark: true,
  },
};

export function getThemeTokens(themeId: ThemeId): ThemeTokenMap {
  return THEME_TOKEN_REGISTRY[themeId] || THEME_TOKEN_REGISTRY.White;
}
